### ISSUE TITLE
CardDialogListener ? or use " setFragmentResultListener()" & "setFragmentResult"

### ISSUE THREAD

**Issue by CMingTseng** [AlexNeiko/teaching.bottomsheetdialogfragment#1]
Dear Sir 

as this  dev guide

https://developer.android.com/guide/fragments/communicate?hl=zh-tw

maybe use   " setFragmentResultListener()" & "setFragmentResult" is bettwer ?

THX

**Comment by AlexNeiko** [comment]
I think it's more complicated. Because you must use Fragment manager. 
And in google case use bundles as data transfer in setFragmentResult. Custom interfece more graceful.
When you use own custom interface and you have more freedom.

**Comment by AlexNeiko** [comment]
The matter is that the call of such dialogue can be not from other fragment. And for example from custom view. You can't always use FragmentManager
